# Generated by Django 3.0 on 2020-04-29 17:54

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(priority='critical', then=django.db.models.expressions.Value(0)), django.db.models.expressions.When(priority='high', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(priority='medium', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(priority='low', then=django.db.models.expressions.Value(3)), output_field=models.IntegerField()), '-creation_time'], 'verbose_name_plural': 'Requests'},
        ),
        migrations.AddField(
            model_name='request',
            name='expiry_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('ongoing_attribution', 'Attributed but not validated'), ('attributed', 'Validated'), ('archived', 'Archived'), ('closed', 'Closed')], default='available', max_length=20),
        ),
    ]
