# Generated by Django 3.0 on 2020-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('ongoing_attribution', 'Attributed but not validated'), ('attributed', 'Validated'), ('archived', 'Archived'), ('closed', 'Closed')], default='available', max_length=20),
        ),
    ]
