# Generated by Django 3.0 on 2020-05-01 12:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_auto_20200501_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(priority=('critical', 'Critical'), then=django.db.models.expressions.Value(0)), django.db.models.expressions.When(priority=('high', 'High'), then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(priority=('medium', 'Medium'), then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(priority=('low', 'Low'), then=django.db.models.expressions.Value(3)), output_field=models.IntegerField()), '-creation_time'], 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[], default=('medium', 'Medium'), max_length=10),
        ),
    ]
