# Generated by Django 3.0 on 2020-05-11 12:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_merge_20200505_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(priority='critical', then=django.db.models.expressions.Value(0)), django.db.models.expressions.When(priority='high', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(priority='medium', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(priority='low', then=django.db.models.expressions.Value(3)), output_field=models.IntegerField()), 'creation_time'], 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
