"""
Django settings for arcv2_platform project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from urllib.parse import urlparse

import sentry_sdk

from sentry_sdk.integrations.django import DjangoIntegration

from arcv2_platform.config.config import config


# init Sentry reporting if sentry_dsn is set
if config.sentry_dsn:
    sentry_sdk.init(
        dsn=config.sentry_dsn,
        environment=config.env,
        server_name=urlparse(config.deployment.base_url).hostname,
        http_proxy=config.http_proxy,
        https_proxy=config.https_proxy,
        send_default_pii=True,
        integrations=[DjangoIntegration()]
    )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.django_secret

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.debug

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'rest_framework',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'widget_tweaks',
    'arcv2_platform.app',
    'arcv2_platform.resources',
    'arcv2_platform.users',
    'arcv2_platform.matchmaking',
    'django_extensions',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'arcv2_platform.app.middlewares.IpFilterMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'arcv2_platform.app.middlewares.TermsOfServiceMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

ROOT_URLCONF = 'arcv2_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'arcv2_platform/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'arcv2_platform.app.context_processors.inject_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'arcv2_platform.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'arcv2_platform/static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'public_static')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '{levelname:<8} {asctime} {module:<10} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': config.loglevels.django,
            'propagate': True,
        },
        'arcv2_platform': {
            'handlers': ['console'],
            'level': config.loglevels.app,
            'propagate': True,
        }
    },
}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config.db.name,
        'USER': config.db.user,
        'PASSWORD': config.db.password,
        'HOST': config.db.host,
        'PORT': config.db.port,
    }
}

# Message engine
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Auth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REDIRECT_URL = '/'

LOGIN_URL = '/users/sso_login'

SSO_HEADERS = {
    'email': 'Remote-User',
    'username': 'Remote-User',
    'firstname': 'Givenname',
    'lastname': 'Surname',
    'affiliation': 'Homeorganization',
    'phone': 'Telephonenumber',
}

# config for the debug toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

EMAIL_BACKEND = config.email.backend

EMAIL_HOST = config.email.host
EMAIL_PORT = config.email.port
EMAIL_HOST_USER = config.email.host_user
EMAIL_HOST_PASSWORD = config.email.host_password
EMAIL_USE_TLS = config.email.use_tls
EMAIL_USE_SSL = config.email.use_ssl
