# Generated by Django 3.0 on 2020-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('affiliation', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_validator', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('has_accepted_tos', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
    ]
