# Generated by Django 3.0 on 2020-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_switch_user',
            field=models.BooleanField(default=False),
        ),
    ]
